package org.example.simplecrud.entity.enums;

public enum Country {
    USA, CANADA, FRANCE, AUSTRALIA, MEXICO, GERMANY,
    JAPAN, BRAZIL, CHINA, SPAIN, UKRAINE, SWITZERLAND,
    THAILAND, ARGENTINA, GREECE, NORWAY, NETHERLANDS,
    ICELAND, PERU, CAMBODIA, AUSTRIA, CROATIA, EGYPT,
    MOROCCO, TURKEY, INDIA, SOUTH_AFRICA, VIETNAM
}
